version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build: .
    container_name: celery_worker
    command: poetry run celery -A tasks worker --loglevel=info -Q scrapy
    depends_on:
      - redis
